spring:
  application:
    name: pos-system

  datasource:
     spring.datasource.url=${DB_URL}
     spring.datasource.username=${DB_USERNAME}
     spring.datasource.password=${DB_PASSWORD}

     spring.jpa.hibernate.ddl-auto=update
     spring.jpa.show-sql=true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: your email
    password: your gmail app password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  devtools:
    livereload:
      enabled: true

server:
  port: 5000

razorpay:
  api:
    key: your razor pay key
    secret: your razorpay secret key

stripe:
  api:
    key: your stripe key



app:
  frontend:
    reset-url: http://localhost:5173/auth/reset-password?token=

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE
