name: Spring Boot CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Java-SaaS-POS-System/Backend

    steps:

      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Give Maven Wrapper Permission
        run: chmod +x mvnw

      - name: Verify Maven
        run: ./mvnw -version

      - name: Clean Project
        run: ./mvnw clean

      - name: Run Test Cases
        run: ./mvnw test

      - name: Build Spring Boot Application
        run: ./mvnw package -DskipTests

  deploy:

    needs: build-and-test

    runs-on: ubuntu-latest

    steps:

      - name: Railway Auto Deployment
        run: echo "Railway automatically deploys after successful GitHub push"
